networks:
  kovatu_net:
services:
  api:
    container_name: kovatu_api
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env
    command: ["sh", "start.sh"]
    ports:
        - "${PORT}:${PORT}"
    networks:
        - kovatu_net
    depends_on:
        - mysql
        - redis_queue
        - redis_cache
  mysql:
    container_name: kovatu_db
    image:  mysql:8.1.0
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - kovatu_net
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no

  redis_queue:
    container_name: kovatu_queue
    image: redis:6.0.12-alpine
    ports:
      - 6379:6379
    networks:
      - kovatu_net

  redis_cache:
    container_name: kovatu_cache
    image: redis:6.0.12-alpine
    ports:
      - 6380:6379
    networks:
      - kovatu_net