networks:
  kovatu_net:
services:
  api:
    container_name: kovatu_api
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env
    command: ["sh", "start.sh"]
    ports:
        - "${PORT}:${PORT}"
    networks:
        - kovatu_net
    depends_on:
        - postgres
        # - redis_queue
        # - redis_cache
  postgres:
    container_name: kovatu_db
    image:  postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - kovatu_net
    environment:
      - POSTGRES_USER=${PG_USER} 
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}

  # redis_queue:
  #   container_name: kovatu_queue
  #   image: redis:6.0.12-alpine
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - kovatu_net

  # redis_cache:
  #   container_name: kovatu_cache
  #   image: redis:6.0.12-alpine
  #   ports:
  #     - 6380:6379
  #   networks:
  #     - kovatu_net